// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import { AurkaSwapVMRouter } from "../src/AurkaSwapVMRouter.sol";
import { DirectSettlement } from "../src/libraries/DirectSettlement.sol";
import { PortfolioBounds } from "../src/libraries/PortfolioBounds.sol";
import { PriceProtection } from "../src/libraries/PriceProtection.sol";
import { ServiceRouterCalldataFixture } from "./ServiceRouterCalldataFixture.sol";
import { TestBase } from "./TestBase.sol";

/// @notice Fixed output from @aurka/services FixtureProposalSigner for the
/// canonical proposal vector. This is a cross-language ABI/signature gate:
/// Solidity must recover the same solver from the service's r || s || v bytes.
contract AurkaServicesInteropTest is TestBase {
    bytes32 internal constant PROPOSAL_HASH =
        0x8119988a84f08a86bc594bf1955a8cc980e0bfda638fc9fc7f94eef891e19ed4;
    address internal constant SERVICE_SOLVER = 0x6370eF2f4Db3611D657b90667De398a2Cc2a370C;
    bytes internal constant SERVICE_SIGNATURE =
        hex"b3355ad2266a1f3021b8386ca7ef6a9352f6a0155f7fc6d351c4186a1414d1b76d92c4be9f720865accc8b4a361e44f6b55903bf156767713dda98c2b1c053971c";

    function testServiceProposalSignatureUsesCanonicalEthereumLayout() public pure {
        bytes memory signature = SERVICE_SIGNATURE;
        bytes32 r;
        bytes32 s;
        uint8 v;
        assembly ("memory-safe") {
            r := mload(add(signature, 0x20))
            s := mload(add(signature, 0x40))
            v := byte(0, mload(add(signature, 0x60)))
        }
        address recovered = ecrecover(PROPOSAL_HASH, v, r, s);
        assertEq(recovered, SERVICE_SOLVER);
        assertEq(v, 28);
    }

    /// @notice The checked-in calldata is generated by the service encoder.
    /// Solidity decodes it using the router's actual tuple types, catching
    /// selector, offsets, struct ordering, and fill-specific amount drift.
    function testGeneratedServiceCalldataDecodesUsingRouterTypes() public pure {
        bytes memory encoded = ServiceRouterCalldataFixture.CALLDATA;
        assertTrue(bytes4(encoded) == 0xd93c3663);
        bytes memory arguments = new bytes(encoded.length - 4);
        for (uint256 i; i < arguments.length; ++i) {
            arguments[i] = encoded[i + 4];
        }

        (
            AurkaSwapVMRouter.Intent memory intent,
            bytes memory intentSignature,
            AurkaSwapVMRouter.Proposal memory proposal,
            bytes memory proposalSignature,
            PortfolioBounds.AssetState[] memory assets,
            DirectSettlement.CapacityEpoch memory epoch,
            PriceProtection.SettlementInput memory priceInput,
            bytes memory directProgram
        ) = abi.decode(
            arguments,
            (
                AurkaSwapVMRouter.Intent,
                bytes,
                AurkaSwapVMRouter.Proposal,
                bytes,
                PortfolioBounds.AssetState[],
                DirectSettlement.CapacityEpoch,
                PriceProtection.SettlementInput,
                bytes
            )
        );

        assertEq(
            intent.intentId, 0x0707070707070707070707070707070707070707070707070707070707070707
        );
        assertEq(proposal.traderInputAmount, ServiceRouterCalldataFixture.TRADER_INPUT_AMOUNT);
        assertEq(proposal.traderOutputAmount, ServiceRouterCalldataFixture.TRADER_OUTPUT_AMOUNT);
        assertEq(priceInput.traderInputAmount, ServiceRouterCalldataFixture.TRADER_INPUT_AMOUNT);
        assertEq(priceInput.traderOutputAmount, ServiceRouterCalldataFixture.TREASURY_OUTPUT_AMOUNT);
        assertEq(epoch.capacityBaseline, 50_000);
        assertEq(assets.length, 3);
        assertEq(intentSignature.length, 0);
        assertEq(proposalSignature.length, 65);
        assertTrue(directProgram.length > 0);
    }
}
